---
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        args: ["--config", ".commitlint.config.js"]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        stages: [pre-commit]
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff-format
        stages: [pre-commit]
