name: Code Quality Check

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Format and Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        name: ruff check
        with:
          version: 0.11.7
          src: "./acapy_controller ./examples"
          args: check
      - uses: astral-sh/ruff-action@v3
        name: ruff format
        with:
          version: 0.11.7
          src: "./acapy_controller ./examples"
          args: format --check
